# Static-site module — S3 + CloudFront.
#
# Intended for client sites generated by the SiteCRM builder that have no
# server component: a React/Vite build (or plain HTML/CSS) uploaded to S3
# and served globally via CloudFront.
#
# Usage (from the root module or a per-site terraform directory):
#
#   module "acme_site" {
#     source        = "../../terraform/modules/static-site"
#     site_name     = "acme-corp"
#     environment   = "prod"
#     custom_domain = "www.acme-corp.com"
#   }
#
# After `terraform apply`, upload the built site:
#   aws s3 sync ./dist "s3://<module.acme_site.bucket_name>" --delete
#   aws cloudfront create-invalidation \
#     --distribution-id <module.acme_site.distribution_id> --paths "/*"

locals {
  name = "${var.site_name}-${var.environment}"
  tags = merge({ ManagedBy = "terraform", Site = var.site_name, Environment = var.environment }, var.tags)
}

# ---------------------------------------------------------------- S3 ----

resource "aws_s3_bucket" "site" {
  bucket = "${local.name}-site"
  tags   = local.tags
}

# Block all direct public access — CloudFront is the only entry point
# via Origin Access Control (OAC), which is the modern successor to OAI.
resource "aws_s3_bucket_public_access_block" "site" {
  bucket                  = aws_s3_bucket.site.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_versioning" "site" {
  bucket = aws_s3_bucket.site.id
  versioning_configuration { status = "Enabled" }
}

# Each `s3 sync --delete` of a rebuilt SPA leaves the old (hashed) assets as
# noncurrent versions. Expire them so storage doesn't grow unbounded across
# deploys while still keeping a short rollback window.
resource "aws_s3_bucket_lifecycle_configuration" "site" {
  bucket = aws_s3_bucket.site.id

  rule {
    id     = "expire-noncurrent-versions"
    status = "Enabled"

    filter {}

    noncurrent_version_expiration {
      noncurrent_days = 30
    }
  }

  depends_on = [aws_s3_bucket_versioning.site]
}

# ------------------------------------------------------------ CloudFront ----

resource "aws_cloudfront_origin_access_control" "site" {
  name                              = local.name
  description                       = "OAC for ${var.site_name}"
  origin_access_control_origin_type = "s3"
  signing_behavior                  = "always"
  signing_protocol                  = "sigv4"
}

locals {
  origin_id = "s3-${local.name}"
}

resource "aws_cloudfront_distribution" "site" {
  enabled             = true
  is_ipv6_enabled     = true
  default_root_object = "index.html"
  price_class         = var.price_class
  aliases             = var.custom_domain != "" ? [var.custom_domain] : []
  tags                = local.tags

  origin {
    domain_name              = aws_s3_bucket.site.bucket_regional_domain_name
    origin_id                = local.origin_id
    origin_access_control_id = aws_cloudfront_origin_access_control.site.id
  }

  default_cache_behavior {
    allowed_methods        = ["GET", "HEAD", "OPTIONS"]
    cached_methods         = ["GET", "HEAD"]
    target_origin_id       = local.origin_id
    viewer_protocol_policy = "redirect-to-https"
    compress               = true

    # Use the AWS-managed caching policy (CachingOptimized).
    cache_policy_id = "658327ea-f89d-4fab-a63d-7e88639e58f6"
  }

  # SPA fallback: return index.html for any 404 so client-side routing works.
  custom_error_response {
    error_code            = 403
    response_code         = 200
    response_page_path    = "/index.html"
    error_caching_min_ttl = 0
  }
  custom_error_response {
    error_code            = 404
    response_code         = 200
    response_page_path    = "/index.html"
    error_caching_min_ttl = 0
  }

  restrictions {
    geo_restriction { restriction_type = "none" }
  }

  viewer_certificate {
    # If a cert ARN is supplied, use it; otherwise fall back to the default
    # CloudFront cert (works only for *.cloudfront.net domains).
    acm_certificate_arn            = var.acm_certificate_arn != "" ? var.acm_certificate_arn : null
    ssl_support_method             = var.acm_certificate_arn != "" ? "sni-only" : null
    minimum_protocol_version       = var.acm_certificate_arn != "" ? "TLSv1.2_2021" : null
    cloudfront_default_certificate = var.acm_certificate_arn == ""
  }
}

# Grant CloudFront (via OAC) read access to the bucket.
resource "aws_s3_bucket_policy" "site" {
  bucket = aws_s3_bucket.site.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "cloudfront.amazonaws.com" }
      Action    = "s3:GetObject"
      Resource  = "${aws_s3_bucket.site.arn}/*"
      Condition = {
        StringEquals = {
          "AWS:SourceArn" = aws_cloudfront_distribution.site.arn
        }
      }
    }]
  })
}
