# Server-app module — ECS Fargate + optional RDS PostgreSQL.
#
# Intended for client apps generated by the SiteCRM builder that require a
# server and/or database: a Fastify/Express container running on Fargate,
# optionally backed by a dedicated RDS PostgreSQL instance.
#
# This module does NOT include an API Gateway or load balancer — wire up
# whichever ingress layer makes sense for the deployment. For a simple
# single-service setup, use the same API Gateway → VPC link → Cloud Map
# pattern as the root SiteCRM infrastructure.
#
# Usage:
#
#   module "acme_portal" {
#     source            = "../../terraform/modules/server-app"
#     site_name         = "acme-portal"
#     vpc_id            = aws_vpc.main.id
#     public_subnet_ids = aws_subnet.public[*].id
#     private_subnet_ids = aws_subnet.private[*].id
#     image_uri         = "123456.dkr.ecr.us-east-1.amazonaws.com/acme-portal:latest"
#     create_database   = true
#   }

locals {
  name = "${var.site_name}-${var.environment}"
  tags = merge({ ManagedBy = "terraform", Site = var.site_name, Environment = var.environment }, var.tags)
}

# ---------------------------------------------------------------- IAM ----

resource "aws_iam_role" "task_execution" {
  name = "${local.name}-exec"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "ecs-tasks.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })

  tags = local.tags
}

resource "aws_iam_role_policy_attachment" "task_execution" {
  role       = aws_iam_role.task_execution.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
}

# Grants ECS the ability to pull the secrets listed in var.secret_arns.
resource "aws_iam_role_policy" "read_secrets" {
  count = length(var.secret_arns) > 0 ? 1 : 0

  name = "read-secrets"
  role = aws_iam_role.task_execution.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect   = "Allow"
      Action   = "secretsmanager:GetSecretValue"
      Resource = values(var.secret_arns)
    }]
  })
}

resource "aws_iam_role" "task" {
  name = "${local.name}-task"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "ecs-tasks.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })

  tags = local.tags
}

# ------------------------------------------------------- security group ----

resource "aws_security_group" "app" {
  name        = local.name
  description = "ECS tasks for ${var.site_name}"
  vpc_id      = var.vpc_id

  ingress {
    description = "App port (from within VPC)"
    from_port   = var.container_port
    to_port     = var.container_port
    protocol    = "tcp"
    cidr_blocks = ["10.0.0.0/8"]
  }

  egress {
    description = "Outbound — image pulls, AWS APIs, database"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = local.tags
}

# ---------------------------------------------------------- (optional) RDS ----

resource "random_password" "db" {
  count   = var.create_database ? 1 : 0
  length  = 32
  special = false
}

resource "aws_db_subnet_group" "app" {
  count      = var.create_database ? 1 : 0
  name       = local.name
  subnet_ids = var.private_subnet_ids
  tags       = local.tags
}

resource "aws_security_group" "db" {
  count       = var.create_database ? 1 : 0
  name        = "${local.name}-db"
  description = "PostgreSQL for ${var.site_name}"
  vpc_id      = var.vpc_id

  ingress {
    description     = "PostgreSQL from the app tasks only"
    from_port       = 5432
    to_port         = 5432
    protocol        = "tcp"
    security_groups = [aws_security_group.app.id]
  }

  tags = local.tags
}

resource "aws_db_instance" "app" {
  count      = var.create_database ? 1 : 0
  identifier = "${local.name}-db"

  engine         = "postgres"
  engine_version = "17"
  instance_class = var.db_instance_class

  allocated_storage = var.db_allocated_storage
  storage_type      = "gp3"
  storage_encrypted = true

  db_name  = var.db_name
  username = var.db_username
  password = random_password.db[0].result

  db_subnet_group_name   = aws_db_subnet_group.app[0].name
  vpc_security_group_ids = [aws_security_group.db[0].id]
  publicly_accessible    = false

  multi_az                = false
  backup_retention_period = 1
  skip_final_snapshot     = true
  deletion_protection     = false
  apply_immediately       = true

  tags = local.tags
}

resource "aws_secretsmanager_secret" "database_url" {
  count                   = var.create_database ? 1 : 0
  name                    = "${local.name}/database-url"
  recovery_window_in_days = 0
  tags                    = local.tags
}

resource "aws_secretsmanager_secret_version" "database_url" {
  count     = var.create_database ? 1 : 0
  secret_id = aws_secretsmanager_secret.database_url[0].id
  secret_string = format(
    "postgres://%s:%s@%s/%s",
    aws_db_instance.app[0].username,
    random_password.db[0].result,
    aws_db_instance.app[0].endpoint,
    var.db_name,
  )
}

# ----------------------------------------------------------------- ECS ----

resource "aws_cloudwatch_log_group" "app" {
  name              = "/ecs/${local.name}"
  retention_in_days = 14
  tags              = local.tags
}

resource "aws_ecs_task_definition" "app" {
  family                   = local.name
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = var.cpu
  memory                   = var.memory
  execution_role_arn       = aws_iam_role.task_execution.arn
  task_role_arn            = aws_iam_role.task.arn

  runtime_platform {
    operating_system_family = "LINUX"
    cpu_architecture        = "X86_64"
  }

  container_definitions = jsonencode([{
    name      = "app"
    image     = var.image_uri
    essential = true

    portMappings = [{ containerPort = var.container_port, protocol = "tcp" }]

    environment = [
      for k, v in var.environment_variables : { name = k, value = v }
    ]

    secrets = concat(
      # Auto-inject DATABASE_URL when this module created the database.
      var.create_database ? [{
        name      = "DATABASE_URL"
        valueFrom = aws_secretsmanager_secret.database_url[0].arn
      }] : [],
      # Caller-supplied secrets.
      [for k, arn in var.secret_arns : { name = k, valueFrom = arn }],
    )

    healthCheck = {
      command     = ["CMD-SHELL", "wget -qO- http://localhost:${var.container_port}/health || exit 1"]
      interval    = 30
      timeout     = 5
      retries     = 3
      startPeriod = 15
    }

    logConfiguration = {
      logDriver = "awslogs"
      options = {
        "awslogs-group"         = aws_cloudwatch_log_group.app.name
        "awslogs-region"        = var.aws_region
        "awslogs-stream-prefix" = "app"
      }
    }
  }])
}

resource "aws_ecs_service" "app" {
  name            = local.name
  cluster         = var.ecs_cluster_id
  task_definition = aws_ecs_task_definition.app.arn
  desired_count   = var.desired_count
  launch_type     = "FARGATE"

  network_configuration {
    subnets          = var.public_subnet_ids
    security_groups  = [aws_security_group.app.id]
    assign_public_ip = true
  }

  force_new_deployment  = true
  wait_for_steady_state = false

  depends_on = [aws_db_instance.app]
}
